### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by gvesuvio** [hassancs91/AI-Content-Ideas-Generator-Prototype#2]
When I run the "app.py" file, I get this error:

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001AC8C88C310>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__  
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close    
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon    
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

the input is:

# Setting input parameters
search_query = "AI in marketing"  # The query to search for
NUMBER_OF_RESULTS = 10  # Number of search results to process

tks :-)

**Comment by hassancs91** [comment]
Did you try running the ui.py steamlit app?

**Comment by gvesuvio** [comment]
Hi, I solved the problem, it was related to the OpenAI API. I confirm that your script works very well. Thanks for your content :)
